#ifndef MESSAGETYPES_H
#define MESSAGETYPES_H

#define MSG_REQ_REGISTER 0x02
#define MSG_REQ_LOGIN 0x03
#define MSG_WELCOME 0x04
#define MSG_AUTH_FAILED 0x05
#define MSG_BROADCAST 0x06
#define MSG_WHISPER 0x07
#define MSG_REGISTR_SUCCESSFUL 0x08
#define MSG_REGISTR_FAILED 0x09
#define MSG_LOGOUT 0xa
#define MSG_WHO 0xb
#define MSG_DISCONNECT 0xc
#define MSG_GRANT_PRIVILEGES 0xd
#define MSG_ADD_FRIEND 0xe
#define MSG_SYSTEM_MSG 0xf
#define MSG_FRIENDS 0x10
#define MSG_REMOVE_FRIEND 0x11
#define MSG_FRIEND_ONLINE 0x12
#define MSG_FRIEND_OFFLINE 0x13
#define MSG_CMD_KICK_ID 0x14
#define MSG_GROUP_CREATE 0x15
#define MSG_GROUP_DELETE 0x16
#define MSG_GROUP_ADD_USER 0x17
#define MSG_GROUP_SEND 0x18
#define MSG_DUMP_ACTIVE_GROUPS 0x19
#define MSG_GROUP_REMOVE_USER 0x1A

#define CMD_CONNECT 2001
#define CMD_DISCONNECT 2002
#define CMD_HELP 2003
#define CMD_INVALID 2004

#endif
